config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :users do
    resources :followers, only: %i[new create]
    resources :hints, only: %i[new create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:destroy]
  resources :sessions, path: 'login', only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/hint.rb
class Hint < ApplicationRecord
  belongs_to :user
  validates :text, length: { in: 4..600 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :fullname, presence: true
  validates :username, uniqueness: true
  # rubocop:disable Metrics/LineLength
  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  has_attached_file :coverimage, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :coverimage, content_type: %r{\Aimage/.*\z}
  has_many :hints, dependent: :destroy
  has_many :active_relationships, class_name: 'Follower', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Follower', foreign_key: 'followed_id', dependent: :destroy
  # rubocop:enable Metrics/LineLength
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def show_hints
    hints.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  def current_user
    User.find_by(username: session[:username])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def new
    @follower = current_user.active_relationships.new(followed_id: params[:user_id])
    if @follower.save
      redirect_to users_path, notice: 'Following.'
    else
      redirect_to users_path, notice: 'cannot follow this user'
    end
  end

  def create; end

  private

  def fol_params
    params.require(:user).permit(:user_id)
  end
end

app/controllers/hints_controller.rb
class HintsController < ApplicationController
  def new; end

  def create
    @hint = current_user.hints.build(hint_params)

    respond_to do |format|
      if @hint.save
        format.html { redirect_to users_path, notice: 'Hint was successfully created.' }
      else
        format.html { redirect_to users_path, notice: 'Hint was not created.' }
      end
    end
  end

  private

  def hint_params
    params.require(:hint).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_username(params[:username])
    if user
      session[:username] = user.username
      redirect_to users_path, notice: 'Logged in!'

    else
      flash.now[:alert] = 'Email or password is invalid'
      redirect_to new_session_path
    end
  end

  def destroy
    session.clear
    redirect_to new_session_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.where.not(id: [[current_user] + current_user.following]).order('created_at DESC')
    @hint = current_user.hints.build
    @hints = Hint.all.order('created_at DESC')
  end

  def show
    @user_show = set_user
    @users = @user_show.followers
    @hints = @user_show.show_hints.order('created_at DESC').includes(:users)
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, notice: 'User name already taken' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :fullname, :image, :coverimage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/hints_helper.rb
module HintsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def add_btn(user)
    ren if user == current_user
  end
end

app/views/hints/_hints.html.erb
 <%= form_for(@hint) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :text, label: "Tweeet about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweeet...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous" />
    <title>TwitterRedesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar columns" role="navigation" aria-label="main navigation">
 <div class=" column first_part">
  <% if logged_in? %>
   <div class="columns is-centered">
<figure class="column">
 <%= image_tag current_user.image.url, class:'p-image'%>
</figure>
     <p class="column is-three-quarters uname"><%= current_user.fullname %></p>
   </div>
  <% end %>
 </div>

  <div class=" column is-three-fifths second_part">
   <span><i class="fas fa-paint-brush"></i></span>
 </div>

<div class=" column third_part">
  <span><i class="fas fa-pencil-alt"></i></span>
  <span><i class="fas fa-envelope"></i></i></span>
  <span><i class="fas fa-search"></i></span>
  <span><i class="fas fa-cog"></i></span>
</div>
</nav>


    <%= yield %>

    

<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>ART HINT</strong> by <a href="https://jgthms.com">ABDOULAYE THE SPY</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CMR</a>.
    </p>
  </div>
</footer>
  </body>
</html>

app/views/users/_following.html.erb
<% @users.each do |user| %>
<div class="flex-container">
<figure class="item">
  <%= image_tag user.image.url, class:'h2-image'%>
</figure>
<div class="item">
	<h1 class="title is-6 name-profile"> <%= user.fullname %> <br> followed by <a href="">The Spy</a></h1>
</div>
<span class="item"> <i class=" plus plus-1 fas fa-plus-circle"></i> </span>
</div>
<% end %>

app/views/users/_form.html.erb
   <main>

  <%= form_for @user do |f| %>

  <div>
  <%= label_tag(:username, "Enter Your Username:") %>
   <%= f.text_field :username,   class:"input is-info", placeholder:"UserName" %>
    
  </div>
  <div>
    <%= label_tag(:fullname, "Enter Your fullname:") %>
    <%= f.text_field :fullname, class:"input is-info", placeholder:"fullname" %>
    <%= label_tag(:image, "Upload profil Image:") %>
    <%=f.file_field :image %> <br>
    <%= label_tag(:image, "Upload Cover Image:") %>
    <%=f.file_field :coverimage %>

  </div>


   <p> <%= f.submit "Create Your Account", class:"button is-primary" %></p>
   
  <% end %>
  </main>

app/views/users/_hints.html.erb
<body>
<% @hints.each do |hint| %>
<div class="hints-areas">
<div class="flex-container">
<figure class="item">
  <%= image_tag hint.user.image.url, class:'p-image'%>
</figure>
<div class="item">
	<h1 class="title is-6"><%= hint.user.fullname %> </h1>
	<%= hint.text %>
</div>
</div>
</div>
<% end %>
</body>

app/views/users/_menu.html.erb
<body>
<div class="columns line1">
   <div class="column line1-1">
      <p class="fol"> <%= current_user.following.count %> </p>
      <p class="fol_num"> Following</p>
   </div>
   <div class="column">
      <p class="fol"> <%= current_user.followers.count %></p>
      <p class="fol_num"> Followers</p>
   </div>
</div>
 
<div class="line2">
 <span><i class="fas fa-home"></i>
 <%= link_to 'HOME',  users_path, class: 'has-text-white-ter title is-6'%> 
 </span>
</div>
<div class="lines">
 <span><i class="fas fa-home"></i></span>CONNECT	
</div>

<div class="lines">
 <span><i class="fas fa-home"></i></span>DISCOVER	
</div>

<div class="lines">
 <span><i class="fas fa-home"></i></span>
 <% if logged_in? %>
 <%= link_to 'PROFILE',  user_path(current_user.id), class: 'has-text-white-ter title is-6'%> 
 <% end %>
</div>

<div class="lines">
 <span><i class="fas fa-home"></i></span>
 <% if logged_in? %>
 <%= link_to 'Logout',  session_path(current_user.id),class: 'has-text-white-ter title is-6', method: :delete%> 
 <% end %>

</div>

</body>

app/views/users/_profile.html.erb
<% @users.each do |user| %>
<div class="flex-container">
<figure class="item">
  <%= image_tag user.image.url, class:'h2-image'%>
</figure>
<div class="item">
	<%= link_to user.fullname,  user_path(user.id), class:'title is-6 name-profile plus' %>
	<h1 class="title is-6 name-profile"> followed by <a href="">The Spy</a></h1>

</div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<body>
   <div class="columns">
      <div class=" column first_part1">
         <%= render 'menu' %>
      </div>
      <div class=" column is-three-fifths part2">
         <div class="part3-1">
            HINTS (ART)
         </div>
         <div class="hint_area">
            <p id="notice"><%= notice %></p>
            <h1>WRITE A HINTS ABOUT A PIECE OR ART</h1>
            <%= form_for(current_user.hints.new, url: user_hints_path(current_user.id)) do |form| %>
            <div> <%= form.text_field :text, id: :comment_content, class: 'input', placeholder: 'Hint' %> </div>
            <%= form.submit 'Create and hint', class: 'button is-link' %>
            <% end %>
        </div>
         <h1 class="sep" >4 NEW HINTS</h1>
         <%= render 'hints'%>
      </div>

      <div class=" column part3">
         <div class="columns part3-2">
            <span class="column is-three-fifths">WHO TO FOLLOW</span>
            <span class="column"><i class="fas fa-expand-arrows-alt"></i></span>
         </div>

         <%= render 'profile' %>
      </div>
   </div>
</body>

app/views/users/new.html.erb
<%= render 'form', user: @user %>
<main>
  <p>Already have an account?</p>
 <%= link_to 'Login', new_session_path, class:"button is-link" %> 
</main>

app/views/users/show.html.erb
<body>
   <div class="columns">
      <div class=" column first_part1">
         <%= render 'menu' %>
      </div>
      <div class=" column is-three-fifths part2">

      <% if logged_in? %>
         <figure class="">
          <%= image_tag current_user.coverimage.url, class:'c-image'%>
      </figure>
      <% end %>
         <div class="part3-1">
            HINTS (ART)
         </div>
         <div class="hint_area">
            <p id="notice"><%= notice %></p>
            <h1>WRITE A HINTS ABOUT A PIECE OR ART</h1>
            <% if logged_in? %>
            <%= form_for(current_user.hints.new, url: user_hints_path(current_user.id)) do |form| %>
            <div> <%= form.text_field :text, id: :comment_content, class: 'input', placeholder: 'Hint' %> </div>
            <%= form.submit 'Create and hint', class: 'button is-link' %>
            <% end %>
            <% end %>
        </div>
         <h1 class="sep" >ALL HINTS/NO COMMENTS</h1>
         <%= render 'hints'%>
      </div>

      <div class=" column part3">
         <div class="columns part3-2">
            <span class="column is-three-fifths">WHO TO FOLLOW</span>
            <span class="column"><i class="fas fa-expand-arrows-alt"></i></span>
         </div>



         <div class="columns part3-3">
          <% if @user_show != current_user %>
           <span class="column add"> <%= link_to '<i class="fas fa-plus-circle"></i>'.html_safe,  new_user_follower_path(@user_show.id), class:'plus' %></span>

           <% else %>
              <span class="column add"> <%= link_to '<i class="fas fa-backward"></i>'.html_safe,  users_path, class:'plus' %></span> 
           <% end %>
             <figure class="column fig is-half">
              <%= image_tag @user_show.image.url, class:'h-image'%>
              <p class="paraph-1"><%= current_user.fullname %></p>
              <p class="paraph-2"><%= current_user.username %></p>
          </figure>
            <span class="column menu"><i class="fas fa-bars"></i></span>
         </div>
         <div class="columns follow">
       <div class="column follow-div">
      <p> <%= @user_show.hints.count %></p>
      <p> Hints</p>
   </div>
   <div class="column follow-div">
      <p> <%= @user_show.following.count %></p>
      <p> Following</p>
   </div>
   <div class="column follow-div">
      <p> <%= current_user.followers.count %> </p>
      <p> Followers</p>
   </div>
</div>

<h1 class="title is-5 fol_by"> FOLLOWED BY</h1>

<%= render 'following' %>
      </div>
   </div>
</body>